### ISSUE TITLE
关于Linux系统通过Zip部署的时候，无法进入MySQL，请问有解决的么，是否我的mysql配置有问题

### ISSUE THREAD

**Issue by rootisnew** [AutohomeCorp/frostmourne#129]
"2022-11-28T16:40:11.466+08:00"	"ERROR"	"com.alibaba.druid.pool.DruidDataSource"	"2781"	"java.sql.SQLSyntaxErrorException"	"Unknown database 'frostmourne'"	"create connection SQLException, url: jdbc:mysql://10.77.77.207:3306/frostmourne, errorCode 1049, state 42000"	"com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread"	"run"	"-"	"-"	"tech"	"frostmourne"	"frostmourne.monitor"	"-"	"214"	"Druid-ConnectionPool-Create-1537689020"	"-"	"127.0.0.1"	"-"	"-"	"-"	"-"	"java.sql.SQLSyntaxErrorException: Unknown database 'frostmourne'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:836)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:197)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:156)
	at com.alibaba.druid.filter.FilterAdapter.connection_connect(FilterAdapter.java:787)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:150)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1646)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1710)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2779)

**Comment by rootisnew** [comment]
可以查看到前段界面，输入账号密码无法进入后端，monitor_error.log日志里面有这个报错

**Comment by rootisnew** [comment]
以上问题已解决，原因： sql文件我尝试导入，但是一直无法导入成功 ，后来修改了字符集设置重新导入成功即可登录界面
