### ISSUE TITLE
1.0版本解密失败

### ISSUE THREAD

**Issue by waney316** [AutohomeCorp/frostmourne#136]
```java
"M
"2023-04-17T14:10:24.788+08:00" "ERROR" "com.autohome.frostmourne.monitor.tool.AESUtils"        "48"    "java.lang.IllegalArgumentException"    "Last encoded character (before the paddings if any) is a valid base 64 alphabet but not a possib
le value. Expected the discarded bits to be zero."      "decrypt exception with data: {""https"":""NO"",""version"":""7.x"",""username"":""elastic"",""password"":""UE6pFk1DX7bWeV7H9521y79B""}"        "com.autohome.frostmourne.monitor.tool.AE
SUtils" "decrypt"       "-"     "-"     "tech"  "frostmourne"   "frostmourne.monitor"   "-"     "205"   "http-nio-10054-exec-2" "-"     "10.64.5.195"   "-"     "-"     "-"     "-"     "java.lang.IllegalArgumentException: Last encoded charact
er (before the paddings if any) is a valid base 64 alphabet but not a possible value. Expected the discarded bits to be zero.
        at org.apache.commons.codec.binary.Base64.validateCharacter(Base64.java:803)
        at org.apache.commons.codec.binary.Base64.decode(Base64.java:482)
        at org.apache.commons.codec.binary.BaseNCodec.decode(BaseNCodec.java:482)
        at org.apache.commons.codec.binary.Base64.decodeBase64(Base64.java:713)
        at com.autohome.frostmourne.monitor.tool.AESUtils.doAES(AESUtils.java:61)
        at com.autohome.frostmourne.monitor.tool.AESUtils.decrypt(AESUtils.java:44)
        at com.autohome.frostmourne.monitor.handler.CryptoTypeHandler.decrypt(CryptoTypeHandler.java:53)
        at com.autohome.frostmourne.monitor.handler.CryptoTypeHandler.getResult(CryptoTypeHandler.java:38)
        at com.autohome.frostmourne.monitor.handler.CryptoTypeHandler.getResult(CryptoTypeHandler.java:18)
        at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.getPropertyMappingValue(DefaultResultSetHandler.java:472)
        at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.applyPropertyMappings(DefaultResultSetHandler.java:441)
        at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.getRowValue(DefaultResultSetHandler.java:404)
        at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleRowValuesForSimpleResultMap(DefaultResultSetHandler.java:354)
        at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleRowValues(DefaultResultSetHandler.java:328)
        at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSet(DefaultResultSetHandler.java:301)
        at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSets(DefaultResultSetHandler.java:194)
        at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:65)
        at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
        at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)
        at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
        at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
        at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
        at com.github.pagehelper.util.ExecutorUtil.pageQuery(ExecutorUtil.java:215)
        at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:128)
        at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
```

目前日志有这个报错，其他的暂时没有发现

**Comment by LittleShrimp1987** [comment]
可能是升级common类库引起的

**Comment by LittleShrimp1987** [comment]
为啥会解密明文

**Comment by waney316** [comment]
> UE6pFk1DX7bWeV7H9521y79B

就是不知道为什么会出现这个报错

**Comment by limboinf** [comment]
老数据吧，可以重新修改下，会自动加密存储，后面就会解密对应的密文了。
