### ISSUE TITLE
添加报警后的错误日志

### ISSUE THREAD

**Issue by wangchaoforever** [AutohomeCorp/frostmourne#140]
版本：[1.0-RELEASE](https://github.com/AutohomeCorp/frostmourne/releases/tag/1.0-RELEASE)

现象：
监控管理=> 监控列表=>添加报警，完成之后，会在日志中定时看到(定时任务1分钟1次)错误日志，如下：

```shell
"2023-05-29T17:22:48.002+08:00"	"ERROR"	"com.autohome.frostmourne.monitor.schedule.RemoteTriggerService"	"35"	"java.lang.IllegalArgumentException"	"URI is not absolute"	"error when trigger remote, id: 18"	"com.autohome.frostmourne.monitor.schedule.RemoteTriggerService"	"trigger"	"-"	"-"tech"	"frostmourne"	"frostmourne.monitor"	"-"	"222"	"JobTriggerHelper-fastTriggerPool243311131"	"-"	"127.0.0.1"	"-"	"-"	"-"	"-"java.lang.IllegalArgumentException: URI is not absolute
	at java.net.URI.toURL(URI.java:1088)
	at org.springframework.http.client.SimpleClientHttpRequestFactory.createRequest(SimpleClientHttpRequestFactory.java:145)
	at org.springframework.http.client.support.HttpAccessor.createRequest(HttpAccessor.java:124)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:735)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:695)
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:324)
	at com.autohome.frostmourne.monitor.schedule.RemoteTriggerService.trigger(RemoteTriggerService.java:29)
	at com.autohome.frostmourne.monitor.schedule.JobTriggerHelper.lambda$addTask$2(JobTriggerHelper.java:55)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by LittleShrimp1987** [comment]
看下这个配置frostmourne_monitor_address的值，需要配置成带http协议的格式。例如：
http://127.0.0.1:10054

**Comment by wangchaoforever** [comment]
按照 http://IP:10054 进行 `frostmourne_monitor_address` 配置之后确实可以了，感谢。
