### ISSUE TITLE
最近用这个工具做ES预警，除了手动点击执行有效果，设置的定时调度为什么没有执行？我看日志也没有运行

### ISSUE THREAD

**Issue by fuxihouyi** [AutohomeCorp/frostmourne#142]
> 倒是在后台看到了这些错误日志
`"2023-06-14T13:49:43.000+08:00" "ERROR" "com.autohome.frostmourne.monitor.schedule.RemoteTriggerService"        "35"    "java.lang.IllegalArgumentException"    "URI is not absolute"   "error when trigger remote, id: 1"   "com.autohome.frostmourne.monitor.schedule.RemoteTriggerService"        "trigger"       "-"     "-"     "tech"  "frostmourne"   "frostmourne.monitor"   "-"     "238"   "JobTriggerHelper-fastTriggerPool86030510"   "-"     "10.0.3.143"    "-"     "-"     "-"     "-"     "java.lang.IllegalArgumentException: URI is not absolute
        at java.net.URI.toURL(URI.java:1088)
        at org.springframework.http.client.SimpleClientHttpRequestFactory.createRequest(SimpleClientHttpRequestFactory.java:145)
        at org.springframework.http.client.support.HttpAccessor.createRequest(HttpAccessor.java:124)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:735)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:695)
        at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:324)
        at com.autohome.frostmourne.monitor.schedule.RemoteTriggerService.trigger(RemoteTriggerService.java:29)
        at com.autohome.frostmourne.monitor.schedule.JobTriggerHelper.lambda$addTask$2(JobTriggerHelper.java:55)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
`

**Comment by LittleShrimp1987** [comment]
https://github.com/AutohomeCorp/frostmourne/issues/140 看看这个issue

**Comment by fuxihouyi** [comment]
哈哈，真的是这样，谢谢大佬，感觉大佬，zip包安装的那块，可以加上这个配置说明，那块没标注这个，我也没有看到

**Comment by fuxihouyi** [comment]
我看日志警告模板中，似乎没有电话号码@的方式，只能在后台配置corpid、agentid、secret。但我们一般可能不能直接拿到自己的corpid、agentid、secret，企业微信台的机器人的@其实还提供了一个电话号码@人的方式，感觉这个可以加上
