### ISSUE TITLE
docker部署，mysql监控，后台会报查询mysql出错。

### ISSUE THREAD

**Issue by weyoung3350** [AutohomeCorp/frostmourne#32]
从后台执行日志看，应该是执行查询时没有传递mysql的密码引起的。
我反复确认过多次，数据源肯定是定义了用户名和密码。我查看data_source表，proterties字段中保存了正确的用户名密码。
并且在新增告警时，页面中的“测试”按钮执行是能正确返回结果的。
============
"2021-01-30T00:34:39.210+08:00" "WARN"  "com.autohome.frostmourne.monitor.service.core.execute.GenerateShortLinkService"        "55"    "-"     "-"     "error when generate short link. response: {""returncode"":0,""message"":""ok"",""result"":""""}"      "com.autohome.frostmourne.monitor.service.core.execute.GenerateShortLinkService" "generate"      "-"     "-"     "tech"  "frostmourne"   "frostmourne.monitor"   "-"     "394"   "Thread-264"    "-"     "172.18.0.4"    "-"     "-"     "-"     "-"     "-"
"2021-01-30T00:34:47.230+08:00" "ERROR" "com.alibaba.druid.pool.DruidDataSource"        "53"    "java.sql.SQLException" "Access denied for user 'xxxxxx'@'10.10.5.220' (using password: YES)"     "create connection error, url: jdbc:mysql://10.10.5.27:3306/xxxxxxx"       "com.alibaba.druid.support.logging.Log4j2Impl"  "error" "-"     "-"     "tech"  "frostmourne"   "frostmourne.monitor"   "-"     "226"   "Druid-ConnectionPool-Create-1187914410"        "-"     "172.18.0.4"    "-"     "-"     "-"    "-"      "java.sql.SQLException: Access denied for user 'xxxxxx'@'10.10.5.220' (using password: YES)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:836)
        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456)
        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:197)
        at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
        at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
        at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1888)

**Comment by LittleShrimp1987** [comment]
最新版本已经修复，镜像还没有更新

**Comment by LittleShrimp1987** [comment]
镜像已经更新
