### ISSUE TITLE
使用ldap登录，返回用户不存在

### ISSUE THREAD

**Issue by Tizeen** [AutohomeCorp/frostmourne#34]
非常感谢此项目，目前在使用的时候，遇到一些问题，希望能白忙之中帮忙解答一下。
谢谢。

## 情况
开启了 ldap 认证之后，登录提示用户不存在（**ldap中是存在登录的用户的，并且在 Jenkins 中配置 ldap 登录，同一用户也能登录 Jenkins**）。

## monitor 版本

部署使用的是 docker-compose ，镜像：

```
registry.cn-hangzhou.aliyuncs.com/kechangqing/frostmourne:0.4
```

## ldap 配置

```
ldap_enabled: 'true'
spring_ldap_urls: ldap://example.com:10389
spring_ldap_username: cn=admin,dc=example,dc=com
spring_ldap_password: xxxxxx
spring_ldap_base: dc=example,dc=com
spring_ldap_auth_searchFilter: uid={0}
```

同样尝试了 `spring_ldap_base` 中指定 `ou`，也是提示用户不存在。

## monitor 报错日志

```
"2021-02-23T11:06:48.684+08:00" "ERROR" "com.autohome.frostmourne.monitor.config.GlobalControllerAdvice"        "24"    "com.autohome.frostmourne.core.contract.ProtocolException"      "用户不存在"    "global catch exception"     "com.autohome.frostmourne.monitor.config.GlobalControllerAdvice"        "handleProtocolException"       "-"     "-"     "tech"  "frostmourne"   "frostmourne.monitor"   "-"     "217"   "http-nio-10054-exec-10"     "-"     "172.20.0.4"    "-"     "-"     "-"     "-"     "com.autohome.frostmourne.core.contract.ProtocolException: 用户不存在
        at com.autohome.frostmourne.monitor.controller.UserController.login(UserController.java:52)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:822)
```

## ldap 日志

发现 ldap 中收到了 2 次请求

```
60347148 conn=1473 fd=28 ACCEPT from IP=172.18.0.1:53676 (IP=0.0.0.0:389)
60347148 conn=1473 op=0 BIND dn="cn=admin,dc=example,dc=com" method=128
60347148 conn=1473 op=0 BIND dn="cn=admin,dc=example,dc=com" mech=SIMPLE ssf=0
60347148 conn=1473 op=0 RESULT tag=97 err=0 text=
60347148 conn=1473 op=1 SRCH base="dc=example,dc=com" scope=2 deref=3 filter="(uid=testuser)"
60347148 conn=1473 op=1 SEARCH RESULT tag=101 err=0 nentries=1 text=
60347148 conn=1473 op=2 UNBIND
60347148 conn=1473 fd=28 closed
60347148 conn=1474 fd=28 ACCEPT from IP=172.18.0.1:53680 (IP=0.0.0.0:389)
60347148 conn=1474 op=0 BIND dn="uid=testuser,ou=People,dc=example,dc=com" method=128
60347148 conn=1474 op=0 BIND dn="uid=testuser,ou=People,dc=example,dc=com" mech=SIMPLE ssf=0
60347148 conn=1474 op=0 RESULT tag=97 err=0 text=
60347148 conn=1474 op=1 UNBIND
60347148 conn=1474 fd=28 closed
```

**Comment by LittleShrimp1987** [comment]
这个报错和ldap没有关系，登录是成功了的，但是在本项目里查testuser用户的时候，没有查到，你需要在frostmourne里添加上testuser账号

**Comment by Tizeen** [comment]
谢谢，问题已解决。
是否考虑在文档中说明一下这点，即使接入 ldap 登录，也需要在系统有对应的用户才能登录。

**Comment by LittleShrimp1987** [comment]
谢谢你的建议，我会在下一次文档更新中增加相关说明

**Comment by LittleShrimp1987** [comment]
文档已经更新
