### ISSUE TITLE
连接https的Elasticsearch失败

### ISSUE THREAD

**Issue by hulengjing** [AutohomeCorp/frostmourne#38]
"2021-03-22T17:33:52.008+08:00" "ERROR" "com.autohome.frostmourne.monitor.dao.elasticsearch.EsRestClientContainer"      "102"   "javax.net.ssl.SSLHandshakeException"   "PKIX path building failed: com.ibm.security.cert.IBMCertPathBuilderException: unable to find valid certification path to requested target"       "error when check cluster health"       "com.autohome.frostmourne.monitor.dao.elasticsearch.EsRestClientContainer"      "health"        "-"     "-"     "tech"  "frostmourne"   "frostmourne.monitor"   "-"     "222"   "http-nio-10054-exec-1" "-"     "10.101.1.211"  "-"     "-"     "-"       "-"     "javax.net.ssl.SSLHandshakeException: PKIX path building failed: com.ibm.security.cert.IBMCertPathBuilderException: unable to find valid certification path to requested target
        at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:947)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:229)
        at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1762)
        at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1732)
        at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1694)
        at org.elasticsearch.client.ClusterClient.health(ClusterClient.java:146)
        at com.autohome.frostmourne.monitor.dao.elasticsearch.EsRestClientContainer.health(EsRestClientContainer.java:100)
        at com.autohome.frostmourne.monitor.dao.elasticsearch.ElasticsearchSourceManager.reloadEsRestClientContainer(ElasticsearchSourceManager.java:47)
        at com.autohome.frostmourne.monitor.service.admin.impl.DataAdminService.saveDataSource(DataAdminService.java:74)
        at com.autohome.frostmourne.monitor.controller.DataNameController.saveDataSource(DataNameController.java:31)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:822)
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: com.ibm.security.cert.IBMCertPathBuilderException: unable to find valid certification path to requested target
        at com.ibm.jsse2.g.a(g.java:58)
        at com.ibm.jsse2.ba.a(ba.java:38)
        at com.ibm.jsse2.ba.a(ba.java:101)
        at com.ibm.jsse2.ba.a(ba.java:62)
        at com.ibm.jsse2.y$c.a(y$c.java:166)
        at com.ibm.jsse2.y$c.a(y$c.java:10)
        at com.ibm.jsse2.y$c.consume(y$c.java:6)
        at com.ibm.jsse2.p.consume(p.java:43)
        at com.ibm.jsse2.Z.a(Z.java:73)
        at com.ibm.jsse2.bf$a$b.a(bf$a$b.java:2)
        at com.ibm.jsse2.bf$a$b.run(bf$a$b.java:3)
        at java.security.AccessController.doPrivileged(AccessController.java:774)
        at com.ibm.jsse2.bf$a.run(bf$a.java:26)
        at org.apache.http.nio.reactor.ssl.SSLIOSession.doRunTask(SSLIOSession.java:288)
        at org.apache.http.nio.reactor.ssl.SSLIOSession.doHandshake(SSLIOSession.java:356)
        at org.apache.http.nio.reactor.ssl.SSLIOSession.isAppInputReady(SSLIOSession.java:537)
        at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:120)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
        ... 1 more
Caused by: com.ibm.jsse2.util.j: PKIX path building failed: com.ibm.security.cert.IBMCertPathBuilderException: unable to find valid certification path to requested target
        at com.ibm.jsse2.util.h.a(h.java:120)
        at com.ibm.jsse2.util.h.b(h.java:5)
        at com.ibm.jsse2.util.g.a(g.java:10)
        at com.ibm.jsse2.bq.a(bq.java:32)
        at com.ibm.jsse2.bq.a(bq.java:70)
        at com.ibm.jsse2.bq.checkServerTrusted(bq.java:10)
        at com.ibm.jsse2.y$c.a(y$c.java:99)
        ... 19 more
Caused by: com.ibm.security.cert.IBMCertPathBuilderException: unable to find valid certification path to requested target
        at com.ibm.security.cert.SunCertPathBuilder.build(SunCertPathBuilder.java:139)
        at com.ibm.security.cert.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:124)
        at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:292)
        at com.ibm.jsse2.util.h.a(h.java:124)
        ... 25 more

**Comment by LittleShrimp1987** [comment]
把堆栈贴出来就行，别把敏感信息贴出来

**Comment by LittleShrimp1987** [comment]
https需要证书文件，目前没有地方配置证书，需要改进

**Comment by LittleShrimp1987** [comment]
可以使用nginx代理es，临时解决一下

**Comment by hulengjing** [comment]
现在目前的情况是ES本身就是ssl的，不支持http，什么时候能上https？  ECK部署现在都是默认ssl的

**Comment by LittleShrimp1987** [comment]
暂时https支持还有问题，临时解决请参考 https://github.com/AutohomeCorp/frostmourne/issues/35 。https的问题我们想一下怎么处理比较好。

**Comment by hulengjing** [comment]
嗯  我这边暂时去掉https了 辛苦帮忙

**Comment by LittleShrimp1987** [comment]
最新版本已经支持https，具体设置参考文档：https://github.com/AutohomeCorp/frostmourne/blob/master/doc/wiki/es.md
