### ISSUE TITLE
添加es数据后 查询报错详细信息请看截图

### ISSUE THREAD

**Issue by shaojielinux** [AutohomeCorp/frostmourne#46]
添加es数据后 [查询报
<img width="1094" alt="WX20210927-175843@2x" src="https://user-images.githubusercontent.com/28892865/134888241-2114d000-8772-496a-82a1-c60155ca035a.png">
错

**Comment by LittleShrimp1987** [comment]
看下程序日志，具体报啥错。

**Comment by shaojielinux** [comment]
我用docker 起的 是看docker的日志吗

**Comment by shaojielinux** [comment]
"reason"":{""type"":""query_shard_exception"",""reason"":""No mapping found for [Time] in order to sort on"",""index_uuid"":""Z0gFyKvaQOKKGZihOggvEg"",""index"":""trade-gaia_api_error-2021.09.27""}}]},""status"":400}
		at org.elasticsearch.client.RestClient$1.completed(RestClient.java:548)
		at org.elasticsearch.client.RestClient$1.completed(RestClient.java:533)
		at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:122)
		at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:181)
		at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:448)
		at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:338)
		at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
		at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
		at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
		at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
		at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
		at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
		at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
		at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
		at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
		at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
		... 1 more

**Comment by shaojielinux** [comment]
<img width="428" alt="图片" src="https://user-images.githubusercontent.com/28892865/134904597-8c64e242-155f-4c0e-a168-d7fbbd5fbe6c.png">
<img width="428" alt="图片" src="https://user-images.githubusercontent.com/28892865/134904598-20eef91b-f9eb-4d0f-9aa6-7adef4f4f033.png">

**Comment by shaojielinux** [comment]
上面的图时间不显示

**Comment by LittleShrimp1987** [comment]
No mapping found for [Time] in order to sort on。 是不是时间字段设置错了
